Repository dev-sec/ansible-ssh-hardening, pull requests merged in 2020-10, with the labels that each got.

#326 update readme to new layout for vars
  README.md
Labels: enhancement

#327 Fix PasswordAuthentication for sftponly
  templates/opensshd.conf.j2
Labels: bug, patch

#328 add SuSE support
  vars/Suse.yml
Labels: enhancement, minor
