Repository dev-sec/ansible-ssh-hardening, pull requests merged in 2020-05, with the labels that each got.

#281 fix: Ansible part of Fedora build
  tests/default.yml
  tests/default_custom.yml
Labels: enhancement, patch

#282 add changelog and release workflow
  .github/workflows/changelog.yml
  .github/workflows/release.yml
Labels: enhancement, minor

#284 make ssh client-side compression configurable
  README.md
  defaults/main.yml
  templates/openssh.conf.j2
Labels: breaking, enhancement
