Repository dev-sec/ansible-ssh-hardening, pull requests merged in 2020-06, with the labels that each got.

#287 allow customization of login gracetime and max sessins
  README.md
  defaults/main.yml
  templates/opensshd.conf.j2
Labels: enhancement, minor

#288 `ssh_allow_tcp_forwarding`: use quotes for values
  README.md
Labels: bug, patch

#289 unify changelog and release actions
  .github/workflows/changelog.yml
  .github/workflows/release.yml
Labels: enhancement, patch

#291 Add archlinux support
  .travis.yml
  meta/main.yml
  tests/default.yml
  tests/default_custom.yml
  vars/Archlinux.yml
Labels: enhancement, minor

#290 Harmonize style
  defaults/main.yml
  handlers/main.yml
  tasks/ca_keys_and_principals.yml
  tasks/crypto.yml
  tasks/hardening.yml
  tasks/main.yml
  tasks/selinux.yml
  templates/authorized_principals.j2
  templates/openssh.conf.j2
  templates/opensshd.conf.j2
  templates/revoked_keys.j2
  templates/trusted_user_ca_keys.j2
  tests/default.yml
  tests/default_custom.yml
  vars/Debian.yml
  vars/Fedora.yml
  vars/FreeBSD.yml
  vars/OpenBSD.yml
  vars/Oracle Linux.yml
  vars/RedHat.yml
  vars/RedHat_8.yml
Labels: enhancement, patch

#298 add centos 8 to meta
  meta/main.yml
Labels: patch
