Repository dev-sec/ansible-ssh-hardening, pull requests merged in 2020-07, with the labels that each got.

#300 allow customization of X11Forwarding
  README.md
  defaults/main.yml
  templates/opensshd.conf.j2
Labels: enhancement, minor

#301 fix package install in tests
  tests/default.yml
  tests/default_custom.yml
Labels: bug, patch

#304 fix typo in hardening.yml
  tasks/hardening.yml
Labels: enhancement, patch

#305 add blocks to crypto.yml checks
  tasks/crypto.yml
  tasks/crypto_ciphers.yml
  tasks/crypto_hostkeys.yml
  tasks/crypto_kex.yml
  tasks/crypto_macs.yml
  tasks/hardening.yml
Labels: enhancement, patch

#312 adding specific things for IPv6 support
  README.md
Labels: enhancement, patch

#314 rework CRYPTO_POLICY handling for fedora
  .kitchen.yml
  files/sshd
  tasks/hardening.yml
  tests/default.yml
  tests/default_custom.yml
  vars/Archlinux.yml
Labels: enhancement, minor

#316 add ssh_banner_path variable
  README.md
  defaults/main.yml
  templates/opensshd.conf.j2
Labels: enhancement

#294 add SmartOS support
  meta/main.yml
  tasks/crypto_hostkeys.yml
  tasks/hardening.yml
  vars/Archlinux.yml
  vars/Debian.yml
  vars/Fedora.yml
  vars/FreeBSD.yml
  vars/OpenBSD.yml
  vars/Oracle Linux.yml
  vars/RedHat.yml
  vars/RedHat_8.yml
  vars/SmartOS.yml
Labels: enhancement, minor

#317 fix sftp_umask; store as literal not octal
  README.md
  defaults/main.yml
Labels: bug, minor

#318 fix local kitchen tests
  .kitchen.yml
Labels: bug, patch
